"""
scripts/create_notebook.py
---------------------------
Generates rq3_citation_link_evaluation.ipynb — a self-contained notebook
that runs the corrected, mathematically rigorous RQ3 Citation Link Agent 
evaluation pipeline end-to-end.

Includes strict one-to-one matching, invalid prediction pre-filtering,
automatic gold-unusable API failure exclusions, and integrity assertions.
"""

import json
from pathlib import Path


def cell_md(source: list[str]) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def cell_code(source: list[str]) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


def build_notebook() -> dict:
    cells = []

    # ── 0. Introduction ──────────────────────────────────────────────────────
    cells.append(cell_md([
        "# RQ3 — Citation Link Agent Evaluation\n",
        "\n",
        "**Research Question:**  \n",
        "> *How accurately can an LLM-based Citation Link Agent extract explicit bibliographic references from academic papers compared with Semantic Scholar reference records?*\n",
        "\n",
        "## Core Evaluation Standards (Evaluator-Corrected)\n",
        "This notebook implements the following methodological corrections to ensure mathematical integrity:\n",
        "1. **Strict One-to-One Matching:** Deduplicates predictions and gold references prior to matching. Once a gold reference is matched to a predicted citation, it is popped from the pool to prevent double-counting.\n",
        "2. **Pre-Scoring Validation:** Requires every prediction to contain at least one usable identifier (Title, DOI, arXiv ID, or Semantic Scholar ID). Empty or malformed LLM outputs are logged in the audit metadata as invalid but are excluded from TP/FP/FN metrics.\n",
        "3. **Gold Database Usability Check:** Automatically detects and excludes papers where the Semantic Scholar API returned zero references while the agent extracted multiple valid citations (representing API database holes rather than true zero-citation baselines).\n",
        "4. **Cache Provenance Verification:** Validates the prompt version, model name, and code hash of `src/agents/link_agent.py` in the prediction cache to ensure experimental reproducibility.\n",
        "5. **Mathematical Integrity Assertions:** Enforces local and global assertions (e.g., $TP + FN == \\text{unique\\_gold}$) at runtime, failing clearly if set boundaries are violated.\n",
        "\n",
        "> [!IMPORTANT]\n",
        "> **RQ1 and RQ2 are completely frozen.** This notebook does not modify `data/generated_notes`, existing Markdown links, embeddings, retrieval indexes, or any RQ1/RQ2 result files.\n",
        "\n",
        "## Expected runtime\n",
        "- **Gold standard build (Cell 2):** ~3 minutes (Semantic Scholar API, 40 papers)\n",
        "- **Citation Link Agent (Cell 3):** seconds (instantly loads from the validated provenance cache)."
    ]))

    # ── 0b. Dependencies ─────────────────────────────────────────────────────
    cells.append(cell_md(["## Cell 0 — Install / Verify Dependencies\n",
                           "Run this cell first to ensure the active Jupyter kernel has all required packages."]))
    cells.append(cell_code([
        "import subprocess, sys\n",
        "pkgs = ['google-generativeai', 'python-dotenv', 'requests', 'pandas']\n",
        "for pkg in pkgs:\n",
        "    try:\n",
        "        __import__(pkg.replace('-', '_').split('>=')[0])\n",
        "    except ImportError:\n",
        "        print(f'Installing {pkg}...')\n",
        "        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg, '-q'])\n",
        "print('[OK] All dependencies present.')",
    ]))

    # ── 1. Imports and config ────────────────────────────────────────────────
    cells.append(cell_md(["## Cell 1 — Imports and Configuration"]))
    cells.append(cell_code([
        "import json, re, sys, time, unicodedata, requests, hashlib\n",
        "from datetime import datetime, timezone\n",
        "from pathlib import Path\n",
        "import pandas as pd\n",
        "\n",
        "try:\n",
        "    from dotenv import load_dotenv\n",
        "    load_dotenv(Path('.env'), override=False)\n",
        "except ImportError:\n",
        "    pass\n",
        "\n",
        "import os\n",
        "S2_API_KEY = os.getenv('S2_API_KEY')\n",
        "assert S2_API_KEY, 'ERROR: S2_API_KEY not found in .env'\n",
        "\n",
        "# Paths\n",
        "NOTES_DIR        = Path('data/generated_notes')\n",
        "EXTRACTED_DIR    = Path('data/extracted_text')\n",
        "GOLD_PATH        = Path('data/gold_labels/rq3_full_reference_gold.json')\n",
        "PREDICTIONS_PATH = Path('data/results/rq3_agent_predictions.json')\n",
        "OUTPUT_PATH      = Path('data/results/rq3_citation_link_evaluation.json')\n",
        "\n",
        "corpus_ids = sorted(p.stem for p in NOTES_DIR.glob('*.md'))\n",
        "corpus_set = set(corpus_ids)\n",
        "assert len(corpus_ids) == 40, f'Expected 40 corpus papers, found {len(corpus_ids)}'\n",
        "print(f'Corpus: {len(corpus_ids)} papers loaded.')\n",
        "print(f'S2_API_KEY: present ({len(S2_API_KEY)} chars)')",
    ]))

    # ── 2. Gold standard build ───────────────────────────────────────────────
    cells.append(cell_md([
        "## Cell 2 — Build Gold Standard (Semantic Scholar API)\n",
        "\n",
        "Queries the full outgoing reference list for each of the 40 corpus papers.  \n",
        "**This cell takes ~3 minutes.** All 40 papers are resolved and paginated completely.\n",
        "\n",
        "References are NOT restricted to the 40-paper corpus — all external references remain in the gold set.\n",
        "\n",
        "*Academic basis: Lo et al. (2020) S2ORC; Kinney et al. (2023) Semantic Scholar Open Data Platform.*",
    ]))
    cells.append(cell_code([
        "S2_HEADERS = {'x-api-key': S2_API_KEY}\n",
        "BASE_URL   = 'https://api.semanticscholar.org/graph/v1/paper'\n",
        "FIELDS     = 'citedPaper.paperId,citedPaper.externalIds,citedPaper.title'\n",
        "LIMIT, DELAY, MAX_RETRIES = 1000, 1.1, 3\n",
        "\n",
        "def resolve_s2_id(arxiv_id):\n",
        "    url = f'{BASE_URL}/arXiv:{arxiv_id}?fields=paperId'\n",
        "    for _ in range(MAX_RETRIES):\n",
        "        r = requests.get(url, headers=S2_HEADERS, timeout=15)\n",
        "        if r.status_code == 200: return r.json().get('paperId')\n",
        "        if r.status_code == 429: time.sleep(60)\n",
        "        elif r.status_code == 404: return None\n",
        "        else: break\n",
        "    return None\n",
        "\n",
        "def fetch_refs(s2_id, arxiv_id):\n",
        "    all_refs, offset = [], 0\n",
        "    while True:\n",
        "        url = f'{BASE_URL}/{s2_id}/references?fields={FIELDS}&limit={LIMIT}&offset={offset}'\n",
        "        for _ in range(MAX_RETRIES):\n",
        "            r = requests.get(url, headers=S2_HEADERS, timeout=30)\n",
        "            if r.status_code == 200: data = r.json().get('data', []); break\n",
        "            if r.status_code == 429: time.sleep(60)\n",
        "            else: data = []; break\n",
        "        else: data = []\n",
        "        if not data: break\n",
        "        for e in data:\n",
        "            cp  = e.get('citedPaper', {})\n",
        "            ext = cp.get('externalIds') or {}\n",
        "            all_refs.append({\n",
        "                's2_paper_id': cp.get('paperId'),\n",
        "                'title':       cp.get('title'),\n",
        "                'doi':         ext.get('DOI'),\n",
        "                'arxiv_id':    ext.get('ArXiv'),\n",
        "                'in_local_corpus': bool(ext.get('ArXiv') and ext['ArXiv'] in corpus_set),\n",
        "            })\n",
        "        offset += LIMIT\n",
        "        time.sleep(DELAY)\n",
        "        if len(data) < LIMIT: break\n",
        "    return all_refs\n",
        "\n",
        "per_paper_gold = {}\n",
        "failed_gold    = []\n",
        "total_gold_refs = 0\n",
        "\n",
        "for i, arxiv_id in enumerate(corpus_ids, 1):\n",
        "    print(f'[{i:02d}/40] {arxiv_id}', end=' ... ')\n",
        "    time.sleep(DELAY)\n",
        "    s2_id = resolve_s2_id(arxiv_id)\n",
        "    if not s2_id:\n",
        "        print('FAILED')\n",
        "        failed_gold.append(arxiv_id)\n",
        "        per_paper_gold[arxiv_id] = {'s2_paper_id': None, 'references': [], 'failed': True}\n",
        "        continue\n",
        "    refs = fetch_refs(s2_id, arxiv_id)\n",
        "    total_gold_refs += len(refs)\n",
        "    per_paper_gold[arxiv_id] = {'s2_paper_id': s2_id, 'references': refs, 'failed': False}\n",
        "    print(f'{len(refs)} refs')\n",
        "\n",
        "gold_timestamp = datetime.now(timezone.utc).isoformat()\n",
        "gold_output = {\n",
        "    'audit_summary': {\n",
        "        'api_query_timestamp':   gold_timestamp,\n",
        "        'corpus_papers':         len(corpus_ids),\n",
        "        'successfully_resolved': len(corpus_ids) - len(failed_gold),\n",
        "        'failed_resolutions':    len(failed_gold),\n",
        "        'failed_arxiv_ids':      failed_gold,\n",
        "        'total_references_fetched': total_gold_refs,\n",
        "    },\n",
        "    'per_paper_references': per_paper_gold,\n",
        "}\n",
        "GOLD_PATH.parent.mkdir(parents=True, exist_ok=True)\n",
        "with open(GOLD_PATH, 'w', encoding='utf-8') as f:\n",
        "    json.dump(gold_output, f, indent=2, ensure_ascii=False)\n",
        "\n",
        "print(f'\\n[OK] Gold standard saved: {len(corpus_ids)-len(failed_gold)}/40 resolved, {total_gold_refs} total references.')\n",
        "if failed_gold: print(f'Failed: {failed_gold}')",
    ]))

    # ── 3. Citation Link Agent ────────────────────────────────────────────────
    cells.append(cell_md([
        "## Cell 3 — Citation Link Agent (Cache-Provenanced)\n",
        "\n",
        "Loads the generated notes predictions. If the cache exists and passes code-hash provenance validation, it loads instantly to protect your API quota. Otherwise, it executes the LLM pipeline.\n",
        "\n",
        "*Academic basis: Tkaczyk et al. (2015) CERMINE; Councill, Giles & Kan (2008) ParsCit.*",
    ]))
    cells.append(cell_code([
        "sys.path.insert(0, '.')\n",
        "from src.agents.link_agent import extract_citation_links, _norm_title\n",
        "\n",
        "# Build corpus title index for local resolution\n",
        "corpus_title_index = {}\n",
        "for note_path in NOTES_DIR.glob('*.md'):\n",
        "    content = note_path.read_text(encoding='utf-8')\n",
        "    m = re.search(r'^title:\\s*[\"\\']?(.*?)[\"\\']?\\s*$', content, re.MULTILINE)\n",
        "    if m:\n",
        "        norm = _norm_title(m.group(1).strip())\n",
        "        if norm: corpus_title_index[norm] = note_path.stem\n",
        "print(f'Corpus title index: {len(corpus_title_index)} entries')\n",
        "\n",
        "agent_predictions = {}\n",
        "if PREDICTIONS_PATH.exists():\n",
        "    try:\n",
        "        with open(PREDICTIONS_PATH, encoding='utf-8') as f:\n",
        "            cached_data = json.load(f)\n",
        "        prov = cached_data.get('provenance_metadata', {})\n",
        "        cached = cached_data.get('predictions', {})\n",
        "        \n",
        "        # Verify agent code hash\n",
        "        agent_code = Path('src/agents/link_agent.py').read_text(encoding='utf-8')\n",
        "        expected_hash = hashlib.sha256(agent_code.encode('utf-8')).hexdigest()\n",
        "        \n",
        "        if (prov.get('agent_code_hash') == expected_hash and \n",
        "            prov.get('model_name') == 'gemini-flash-latest' and\n",
        "            prov.get('temperature') == 0.0 and\n",
        "            prov.get('prompt_version') == 'v1' and\n",
        "            all(cid in cached for cid in corpus_ids) and len(cached) == 40):\n",
        "            agent_predictions = cached\n",
        "            print('[OK] Loaded predictions from cache (rq3_agent_predictions.json). Skipping LLM API calls!')\n",
        "        else:\n",
        "            print('Provenance check failed. Re-running LLM API calls...')\n",
        "    except Exception as e:\n",
        "        print(f'Cache loading failed: {e}. Running API calls...')\n",
        "\n",
        "if not agent_predictions:\n",
        "    print('No complete predictions cache found. Running Citation Link Agent on 40 papers...')\n",
        "    for i, arxiv_id in enumerate(corpus_ids, 1):\n",
        "        ext_path = EXTRACTED_DIR / f'{arxiv_id}.json'\n",
        "        if not ext_path.exists():\n",
        "            print(f'[{i:02d}/40] {arxiv_id} — no extracted text, skipping')\n",
        "            agent_predictions[arxiv_id] = {'references': [], 'error': 'no_extracted_text', 'section_fallback': False}\n",
        "            continue\n",
        "        doc       = json.load(open(ext_path, encoding='utf-8'))\n",
        "        full_text = doc.get('text', '')\n",
        "        if not full_text.strip():\n",
        "            print(f'[{i:02d}/40] {arxiv_id} — empty text, skipping')\n",
        "            agent_predictions[arxiv_id] = {'references': [], 'error': 'empty_text', 'section_fallback': False}\n",
        "            continue\n",
        "        result = extract_citation_links(full_text, corpus_index=corpus_title_index)\n",
        "        refs   = result.get('references', [])\n",
        "        local  = sum(1 for r in refs if r.get('local_arxiv_id'))\n",
        "        fb     = '[FALLBACK] ' if result.get('section_fallback') else ''\n",
        "        print(f'[{i:02d}/40] {arxiv_id} — {fb}{len(refs)} refs ({local} local)')\n",
        "        agent_predictions[arxiv_id] = result\n",
        "        time.sleep(1.0)\n",
        "\n",
        "    # Re-save with provenance metadata\n",
        "    agent_code = Path('src/agents/link_agent.py').read_text(encoding='utf-8')\n",
        "    code_hash = hashlib.sha256(agent_code.encode('utf-8')).hexdigest()\n",
        "    wrapped = {\n",
        "        'provenance_metadata': {\n",
        "            'model_name': 'gemini-flash-latest',\n",
        "            'temperature': 0.0,\n",
        "            'prompt_version': 'v1',\n",
        "            'agent_code_hash': code_hash,\n",
        "            'creation_timestamp': datetime.now(timezone.utc).isoformat()\n",
        "        },\n",
        "        'predictions': agent_predictions\n",
        "    }\n",
        "    PREDICTIONS_PATH.parent.mkdir(parents=True, exist_ok=True)\n",
        "    with open(PREDICTIONS_PATH, 'w', encoding='utf-8') as f:\n",
        "        json.dump(wrapped, f, indent=2, ensure_ascii=False)\n",
        "    print('[OK] Agent predictions saved with provenance.')\n",
        "\n",
        "    total_preds = sum(len(v.get('references', [])) for v in agent_predictions.values())\n",
        "    print(f'Total references extracted: {total_preds}')\n",
    ]))

    # ── 4. Evaluate ───────────────────────────────────────────────────────────
    cells.append(cell_md([
        "## Cell 4 — Strict Transitive Deduplication & Evaluation\n",
        "\n",
        "This cell implements transitive deduplication, status flag filters (excluding provider blocks and gold database failures), and sequential one-to-one matching."
    ]))
    cells.append(cell_code([
        "def norm_arxiv(v):\n",
        "    if not v: return None\n",
        "    return re.sub(r'v\\d+$', '', str(v).strip().lower())\n",
        "def norm_doi(v): return str(v).strip().lower() if v else None\n",
        "def norm_s2(v):  return str(v).strip() if v else None\n",
        "def norm_t(v):\n",
        "    if not v: return None\n",
        "    t = unicodedata.normalize('NFKD', str(v).lower())\n",
        "    t = re.sub(r'[^\\w\\s]', ' ', t)\n",
        "    return re.sub(r'\\s+', ' ', t).strip()\n",
        "\n",
        "def jaccard(a, b):\n",
        "    if not a or not b: return 0.0\n",
        "    sa, sb = set(a.split()), set(b.split())\n",
        "    return len(sa & sb) / len(sa | sb) if (sa or sb) else 0.0\n",
        "\n",
        "def fuzzy_cands(agent_ref, gold_refs, thr=0.55):\n",
        "    at = norm_t(agent_ref.get('title'))\n",
        "    if not at: return []\n",
        "    c = [{'gold_title': r.get('title'), 'score': round(jaccard(at, norm_t(r.get('title')) or ''), 4)}\n",
        "         for r in gold_refs if jaccard(at, norm_t(r.get('title')) or '') >= thr]\n",
        "    return sorted(c, key=lambda x: -x['score'])[:5]\n",
        "\n",
        "def deduplicate_references(refs):\n",
        "    unique_refs = []\n",
        "    invalid_count = 0\n",
        "    for ref in refs:\n",
        "        s2, doi, arx, tit = norm_s2(ref.get('s2_paper_id')), norm_doi(ref.get('doi')), norm_arxiv(ref.get('arxiv_id')), norm_t(ref.get('title'))\n",
        "        if not any([s2, doi, arx, tit]):\n",
        "            invalid_count += 1\n",
        "            continue\n",
        "        is_duplicate = False\n",
        "        for u in unique_refs:\n",
        "            if s2 and norm_s2(u.get('s2_paper_id')) == s2: is_duplicate = True; break\n",
        "            if doi and norm_doi(u.get('doi')) == doi: is_duplicate = True; break\n",
        "            if arx and norm_arxiv(u.get('arxiv_id')) == arx: is_duplicate = True; break\n",
        "            if tit and norm_t(u.get('title')) == tit: is_duplicate = True; break\n",
        "        if not is_duplicate:\n",
        "            unique_refs.append(ref)\n",
        "    return unique_refs, invalid_count\n",
        "\n",
        "global_tp = global_fp = global_fn = 0\n",
        "match_counts = {'s2_id': 0, 'doi': 0, 'arxiv_id': 0, 'exact_title': 0}\n",
        "per_paper_results = {}\n",
        "invalid_outputs_count = 0\n",
        "excluded_gold_unusable = []\n",
        "excluded_provider_blocks = []\n",
        "per_paper_totals_sum = {'tp': 0, 'fp': 0, 'fn': 0}\n",
        "\n",
        "for arxiv_id in corpus_ids:\n",
        "    gold_paper = per_paper_gold.get(arxiv_id, {})\n",
        "    gold_refs  = gold_paper.get('references', [])\n",
        "    agent_data = agent_predictions.get(arxiv_id, {})\n",
        "    agent_refs = agent_data.get('references', [])\n",
        "    agent_status = agent_data.get('status', 'success')\n",
        "    \n",
        "    if gold_paper.get('failed'):\n",
        "        per_paper_results[arxiv_id] = {'status': 'gold_unusable', 'tp': 0, 'fp': 0, 'fn': 0}\n",
        "        continue\n",
        "        \n",
        "    # 1. Deduplicate references transitively\n",
        "    unique_gold, _ = deduplicate_references(gold_refs)\n",
        "    unique_preds, invalid_cnt = deduplicate_references(agent_refs)\n",
        "    invalid_outputs_count += invalid_cnt\n",
        "    \n",
        "    # 2. Exclude gold unusable (API failures returning 0 refs when agent found refs)\n",
        "    if len(unique_gold) == 0 and len(unique_preds) > 0:\n",
        "        excluded_gold_unusable.append(arxiv_id)\n",
        "        per_paper_results[arxiv_id] = {'status': 'gold_unusable', 'tp': 0, 'fp': 0, 'fn': 0}\n",
        "        continue\n",
        "        \n",
        "    # 3. Exclude provider blocks from evaluation scope\n",
        "    if agent_status == 'provider_block':\n",
        "        excluded_provider_blocks.append(arxiv_id)\n",
        "        per_paper_results[arxiv_id] = {'status': 'provider_block', 'tp': 0, 'fp': 0, 'fn': 0}\n",
        "        continue\n",
        "        \n",
        "    # 4. Strict One-to-One Matching\n",
        "    gold_pool = list(unique_gold)\n",
        "    matched_gold_indices = set()\n",
        "    paper_tp = paper_fp = 0\n",
        "    records = []\n",
        "    \n",
        "    for ref in unique_preds:\n",
        "        match_found = False\n",
        "        \n",
        "        s2 = norm_s2(ref.get('s2_paper_id'))\n",
        "        if s2:\n",
        "            for idx, g in enumerate(gold_pool):\n",
        "                if idx not in matched_gold_indices and norm_s2(g.get('s2_paper_id')) == s2:\n",
        "                    matched_gold_indices.add(idx)\n",
        "                    match_counts['s2_id'] = match_counts.get('s2_id', 0) + 1\n",
        "                    paper_tp += 1\n",
        "                    records.append({'agent_title': ref.get('title'), 'matched': g.get('title'), 'match_type': 's2_id', 'result': 'TP'})\n",
        "                    match_found = True\n",
        "                    break\n",
        "        if match_found: continue\n",
        "        \n",
        "        doi = norm_doi(ref.get('doi'))\n",
        "        if doi:\n",
        "            for idx, g in enumerate(gold_pool):\n",
        "                if idx not in matched_gold_indices and norm_doi(g.get('doi')) == doi:\n",
        "                    matched_gold_indices.add(idx)\n",
        "                    match_counts['doi'] = match_counts.get('doi', 0) + 1\n",
        "                    paper_tp += 1\n",
        "                    records.append({'agent_title': ref.get('title'), 'matched': g.get('title'), 'match_type': 'doi', 'result': 'TP'})\n",
        "                    match_found = True\n",
        "                    break\n",
        "        if match_found: continue\n",
        "        \n",
        "        arx = norm_arxiv(ref.get('arxiv_id'))\n",
        "        if arx:\n",
        "            for idx, g in enumerate(gold_pool):\n",
        "                if idx not in matched_gold_indices and norm_arxiv(g.get('arxiv_id')) == arx:\n",
        "                    matched_gold_indices.add(idx)\n",
        "                    match_counts['arxiv_id'] = match_counts.get('arxiv_id', 0) + 1\n",
        "                    paper_tp += 1\n",
        "                    records.append({'agent_title': ref.get('title'), 'matched': g.get('title'), 'match_type': 'arxiv_id', 'result': 'TP'})\n",
        "                    match_found = True\n",
        "                    break\n",
        "        if match_found: continue\n",
        "        \n",
        "        tit = norm_t(ref.get('title'))\n",
        "        if tit:\n",
        "            for idx, g in enumerate(gold_pool):\n",
        "                if idx not in matched_gold_indices and norm_t(g.get('title')) == tit:\n",
        "                    matched_gold_indices.add(idx)\n",
        "                    match_counts['exact_title'] = match_counts.get('exact_title', 0) + 1\n",
        "                    paper_tp += 1\n",
        "                    records.append({'agent_title': ref.get('title'), 'matched': g.get('title'), 'match_type': 'exact_title', 'result': 'TP'})\n",
        "                    match_found = True\n",
        "                    break\n",
        "        if match_found: continue\n",
        "        \n",
        "        paper_fp += 1\n",
        "        records.append({'agent_title': ref.get('title'), 'result': 'FP', 'fuzzy_match_candidates': fuzzy_cands(ref, gold_pool)})\n",
        "        \n",
        "    paper_fn = len(gold_pool) - len(matched_gold_indices)\n",
        "    fn_list = [gold_pool[i] for i in range(len(gold_pool)) if i not in matched_gold_indices]\n",
        "    \n",
        "    # Assert local paper level integrity\n",
        "    assert paper_tp + paper_fn == len(unique_gold), f'Math discrepancy in {arxiv_id}'\n",
        "    assert paper_tp + paper_fp == len(unique_preds), f'Math discrepancy in {arxiv_id}'\n",
        "    \n",
        "    global_tp += paper_tp\n",
        "    global_fp += paper_fp\n",
        "    global_fn += paper_fn\n",
        "    \n",
        "    per_paper_totals_sum['tp'] += paper_tp\n",
        "    per_paper_totals_sum['fp'] += paper_fp\n",
        "    per_paper_totals_sum['fn'] += paper_fn\n",
        "    \n",
        "    per_paper_results[arxiv_id] = {\n",
        "        'status': agent_status, 'tp': paper_tp, 'fp': paper_fp, 'fn': paper_fn,\n",
        "        'gold_refs': unique_gold, 'preds': unique_preds, 'agent_records': records, 'false_negatives': fn_list\n",
        "    }\n",
        "\n",
        "# Assert global totals sum matching\n",
        "scored_papers = [p for p in corpus_ids if per_paper_results[p]['status'] not in ['gold_unusable', 'provider_block']]\n",
        "assert global_tp == per_paper_totals_sum['tp'], 'Global TP mismatch'\n",
        "assert global_fp == per_paper_totals_sum['fp'], 'Global FP mismatch'\n",
        "assert global_fn == per_paper_totals_sum['fn'], 'Global FN mismatch'\n",
        "\n",
        "precision = global_tp / (global_tp + global_fp) if (global_tp + global_fp) > 0 else 0.0\n",
        "recall    = global_tp / (global_tp + global_fn) if (global_tp + global_fn) > 0 else 0.0\n",
        "f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0\n",
        "\n",
        "print('='*60)\n",
        "print('RQ3 — CITATION LINK AGENT RESULTS (CORRECTED CORPUS)')\n",
        "print('='*60)\n",
        "df = pd.DataFrame([\n",
        "    {'Metric': 'True Positives (TP)',  'Value': global_tp},\n",
        "    {'Metric': 'False Positives (FP)', 'Value': global_fp},\n",
        "    {'Metric': 'False Negatives (FN)', 'Value': global_fn},\n",
        "    {'Metric': 'Precision',            'Value': f'{precision:.4f}'},\n",
        "    {'Metric': 'Recall',               'Value': f'{recall:.4f}'},\n",
        "    {'Metric': 'F1-Score',             'Value': f'{f1:.4f}'},\n",
        "])\n",
        "print(df.to_string(index=False))\n",
        "print(f'\\nMatch type breakdown: {match_counts}')\n",
        "print(f'Invalid agent outputs filtered: {invalid_outputs_count}')\n",
        "print(f'Gold unusable papers excluded (API failures): {excluded_gold_unusable}')\n",
        "print(f'Provider blocked papers excluded: {excluded_provider_blocks}')\n",
        "print(f'Scored papers count: {len(scored_papers)}/40')",
    ]))

    # ── 5. Save ───────────────────────────────────────────────────────────────
    cells.append(cell_md(["## Cell 5 — Save Final Results"]))
    cells.append(cell_code([
        "final_output = {\n",
        "    'audit_metadata': {\n",
        "        'evaluation_timestamp': datetime.now(timezone.utc).isoformat(),\n",
        "        'research_question':    'How accurately can an LLM-based Citation Link Agent extract explicit bibliographic references from academic papers compared with Semantic Scholar reference records?',\n",
        "        'gold_build_timestamp': gold_timestamp,\n",
        "        'gold_papers_resolved': len(corpus_ids) - len(failed_gold),\n",
        "        'gold_total_references': total_gold_refs,\n",
        "        'rq1_rq2_frozen': True,\n",
        "        'one_to_one_matching': True,\n",
        "        'transitive_deduplication': True,\n",
        "        'invalid_agent_outputs_filtered': invalid_outputs_count,\n",
        "        'excluded_gold_unusable_papers': excluded_gold_unusable,\n",
        "        'excluded_provider_blocked_papers': excluded_provider_blocks,\n",
        "        'scored_papers_count': len(scored_papers),\n",
        "    },\n",
        "    'overall_metrics': {\n",
        "        'true_positives':  global_tp,\n",
        "        'false_positives': global_fp,\n",
        "        'false_negatives': global_fn,\n",
        "        'precision':       round(precision, 5),\n",
        "        'recall':          round(recall, 5),\n",
        "        'f1':              round(f1, 5),\n",
        "        'match_type_breakdown': match_counts,\n",
        "    },\n",
        "    'per_paper_results': per_paper_results,\n",
        "}\n",
        "OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)\n",
        "with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:\n",
        "    json.dump(final_output, f, indent=2, ensure_ascii=False)\n",
        "print(f'[OK] Results saved to {OUTPUT_PATH}')",
    ]))

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbformat_minor": 5,
                "pygments_lexer": "ipython3",
                "version": "3.10.0",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


if __name__ == "__main__":
    nb = build_notebook()
    out = Path("rq3_citation_link_evaluation.ipynb")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=2)
    print(f"Notebook written to {out}")
