"""
scripts/evaluate_links.py

Description:
    Evaluates the quality of predicted paper-to-paper links generated by the multi-agent ingestion pipeline
    against the new audited Semantic Scholar citation graph:
    `data/gold_labels/rq3_semantic_scholar_internal_citation_edges.json`

    Evaluation Logic:
    1. Validation: Ensures that the gold standard graph is fresh, has no duplicates, matches the 40 corpus notes,
       and resolved 40/40 papers. If any check fails, the evaluation halts with an error.
    2. Primary Result: Strict Directed Precision, Recall, and F1.
    3. Secondary Analysis: Undirected Pair Precision, Recall, and F1.
"""

import json
import re
import sys
import time
from pathlib import Path

def parse_predicted_links(notes_dir: Path, title_to_arxiv: dict) -> list[dict]:
    """
    Scan generated notes and parse predicted links under the ## Generated Links header.
    """
    predicted_links = []
    
    for note_path in notes_dir.glob("*.md"):
        source_id = note_path.stem  # arXiv ID
        try:
            content = note_path.read_text(encoding="utf-8")
        except Exception as e:
            print(f"Error reading {note_path}: {e}")
            continue
            
        parts = content.split("## Generated Links")
        if len(parts) < 2:
            continue
            
        links_section = parts[1]
        lines = links_section.strip().split("\n")
        
        for line in lines:
            line = line.strip()
            if not line.startswith("-"):
                continue
                
            match = re.search(r"-\s*\*\*\[\[(.*?)\]\]\*\*\s*\((.*?)\)", line)
            if match:
                target_title = match.group(1).strip()
                target_id = title_to_arxiv.get(target_title.lower())
                
                if target_id:
                    predicted_links.append({
                        "source": source_id,
                        "target": target_id
                    })
                    
    return predicted_links

def main():
    notes_dir = Path("data/generated_notes")
    gold_path = Path("data/gold_labels/rq3_semantic_scholar_internal_citation_edges.json")
    output_path = Path("data/results/link_eval.json")
    
    # Pre-check paths
    if not notes_dir.exists():
        print("Error: Generated notes directory does not exist.")
        sys.exit(1)
        
    if not gold_path.exists():
        print(f"Error: Audited gold citation file '{gold_path}' does not exist. Please run build_citation_gold.py first.")
        sys.exit(1)

    # 1. Load predicted links and build corpus arXiv set
    title_to_arxiv = {}
    for note_path in notes_dir.glob("*.md"):
        arxiv_id = note_path.stem
        try:
            content = note_path.read_text(encoding="utf-8")
        except Exception:
            continue
        title_match = re.search(r'^title:\s*"(.*?)"', content, re.MULTILINE)
        if not title_match:
            title_match = re.search(r'^title:\s*(.*?)$', content, re.MULTILINE)
        if title_match:
            title = title_match.group(1).strip().strip('"').strip("'")
            title_to_arxiv[title.lower()] = arxiv_id

    predicted_links = parse_predicted_links(notes_dir, title_to_arxiv)
    corpus_arxiv_ids = {p.stem for p in notes_dir.glob("*.md")}
    
    if len(corpus_arxiv_ids) != 40:
        print(f"Error: Expected exactly 40 corpus notes, found {len(corpus_arxiv_ids)}")
        sys.exit(1)

    # 2. Load and validate the gold standard
    try:
        with open(gold_path, encoding="utf-8") as f:
            gold_data = json.load(f)
    except Exception as e:
        print(f"Error: Failed to parse gold citation JSON: {e}")
        sys.exit(1)

    audit = gold_data.get("audit_summary", {})
    edges = gold_data.get("citation_edges", [])

    # Validation check: Freshness (within 1 hour)
    file_mod_time = gold_path.stat().st_mtime
    time_diff = time.time() - file_mod_time
    if time_diff > 3600:
        print(f"Validation Failed: Gold citation file is stale (created {time_diff/60:.1f} minutes ago). Please rebuild it.")
        sys.exit(1)

    # Validation check: Resolution completeness
    if audit.get("corpus_papers") != 40:
        print(f"Validation Failed: Audit summary corpus papers count is {audit.get('corpus_papers')}, expected 40.")
        sys.exit(1)
        
    if audit.get("successfully_resolved") != 40:
        print(f"Validation Failed: Resolved papers count is {audit.get('successfully_resolved')}, expected 40.")
        sys.exit(1)
        
    if audit.get("failed_resolutions"):
        print(f"Validation Failed: Found unresolved papers in audit summary: {audit.get('failed_resolutions')}")
        sys.exit(1)

    # Validation check: Source and target membership
    for idx, edge in enumerate(edges):
        src = edge.get("source")
        tgt = edge.get("target")
        if src not in corpus_arxiv_ids:
            print(f"Validation Failed: Gold edge #{idx} contains source '{src}' which is not in the 40-paper corpus.")
            sys.exit(1)
        if tgt not in corpus_arxiv_ids:
            print(f"Validation Failed: Gold edge #{idx} contains target '{tgt}' which is not in the 40-paper corpus.")
            sys.exit(1)

    # Validation check: No duplicates
    edge_tuples = [(e["source"], e["target"]) for e in edges]
    if len(edge_tuples) != len(set(edge_tuples)):
        print("Validation Failed: Found duplicate directed edges in the gold citation file.")
        sys.exit(1)

    print("[OK] Gold Graph Validation Checks Passed successfully!\n")

    # Define edge sets
    pred_edges_dir = {(l["source"], l["target"]) for l in predicted_links}
    gold_edges_dir = {(src, tgt) for src, tgt in edge_tuples}

    # =========================================================================
    # 1. Primary Evaluation: Strict Directed Metrics
    # =========================================================================
    tp_dir = len(pred_edges_dir & gold_edges_dir)
    fp_dir = len(pred_edges_dir - gold_edges_dir)
    fn_dir = len(gold_edges_dir - pred_edges_dir)
    
    p_dir = tp_dir / len(pred_edges_dir) if pred_edges_dir else 0.0
    r_dir = tp_dir / len(gold_edges_dir) if gold_edges_dir else 0.0
    f1_dir = 2 * p_dir * r_dir / (p_dir + r_dir) if p_dir + r_dir > 0 else 0.0

    # =========================================================================
    # 2. Secondary Analysis: Undirected Pair Metrics
    # =========================================================================
    pred_edges_undir = {frozenset([u, v]) for u, v in pred_edges_dir}
    gold_edges_undir = {frozenset([u, v]) for u, v in gold_edges_dir}
    
    tp_undir = len(pred_edges_undir & gold_edges_undir)
    fp_undir = len(pred_edges_undir - gold_edges_undir)
    fn_undir = len(gold_edges_undir - pred_edges_undir)
    
    p_undir = tp_undir / len(pred_edges_undir) if pred_edges_undir else 0.0
    r_undir = tp_undir / len(gold_edges_undir) if gold_edges_undir else 0.0
    f1_undir = 2 * p_undir * r_undir / (p_undir + r_undir) if p_undir + r_undir > 0 else 0.0

    # 4. Compile and save results
    results = {
        "evaluation_scope": "RQ3 - Link Prediction Reliability (Sole Gold Standard: Semantic Scholar API)",
        "hypothesis": "H3: The Link Agent will identify a meaningful proportion of the directed citation links between papers in the corpus, although some errors are expected because the agent predicts links from paper summaries rather than complete reference lists.",
        "directed_evaluation_primary": {
            "true_positives": tp_dir,
            "false_positives": fp_dir,
            "false_negatives": fn_dir,
            "precision": round(p_dir, 5),
            "recall": round(r_dir, 5),
            "f1": round(f1_dir, 5)
        },
        "undirected_evaluation_secondary": {
            "true_positives": tp_undir,
            "false_positives": fp_undir,
            "false_negatives": fn_undir,
            "precision": round(p_undir, 5),
            "recall": round(r_undir, 5),
            "f1": round(f1_undir, 5)
        }
    }
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    # Print formatted output
    print("="*70)
    print("                RQ3 LINK EVALUATION RESULTS (API ONLY)")
    print("="*70)
    print("PRIMARY RESULT: STRICT DIRECTED CITATIONS")
    print(f"  True Positives (TP): {tp_dir}")
    print(f"  False Positives (FP): {fp_dir}")
    print(f"  False Negatives (FN): {fn_dir}")
    print(f"  Directed Precision:  {p_dir:.5f}")
    print(f"  Directed Recall:     {r_dir:.5f}")
    print(f"  Directed F1-score:   {f1_dir:.5f}")
    print("-"*70)
    print("SECONDARY ANALYSIS: UNDIRECTED PAIR IDENTIFICATION")
    print(f"  True Positives (TP): {tp_undir}")
    print(f"  False Positives (FP): {fp_undir}")
    print(f"  False Negatives (FN): {fn_undir}")
    print(f"  Pair Precision:      {p_undir:.5f}")
    print(f"  Pair Recall:         {r_undir:.5f}")
    print(f"  Pair F1-score:       {f1_undir:.5f}")
    print("="*70 + "\n")
    print(f"Results successfully saved to {output_path}")

if __name__ == "__main__":
    main()
