"""
scripts/evaluate_links.py

Description:
    Evaluates the quality of predicted paper-to-paper links generated by the multi-agent ingestion pipeline
    against two distinct gold standard graphs (RQ3):

    1. Level A (Global Citations - N=40):
       Objective citation graph retrieved from the Semantic Scholar API. We evaluate predicted links
       across all 40 papers against the actual citations that exist in the academic literature.

    2. Level B (Personal Vault - N=22):
       Subjective, personal relationships curated in Emile's Obsidian vault. To ensure fairness,
       we restrict this comparison strictly to the 22 shared papers present in both the expert vault
       and our corpus.

    Matching Logic:
    - Directed edge matching (A -> B). If the agent predicts A -> B but the gold is B -> A, it is not a match.
    - No link relation types (extends, comparesTo, etc.) are evaluated to avoid vocabulary mismatch errors.

    Metrics computed:
    - Directed Precision
    - Directed Recall
    - Directed F1-score
    - Count of predicted and gold links
"""

import json
import re
from pathlib import Path

def parse_predicted_links(notes_dir: Path, title_to_arxiv: dict) -> list[dict]:
    """
    Scan generated notes and parse predicted links under the ## Generated Links header.
    Resolves targets to arXiv IDs using the title resolver map.
    """
    predicted_links = []
    
    for note_path in notes_dir.glob("*.md"):
        source_id = note_path.stem  # arXiv ID
        try:
            content = note_path.read_text(encoding="utf-8")
        except Exception as e:
            print(f"Error reading {note_path}: {e}")
            continue
            
        parts = content.split("## Generated Links")
        if len(parts) < 2:
            continue
            
        links_section = parts[1]
        lines = links_section.strip().split("\n")
        
        for line in lines:
            line = line.strip()
            if not line.startswith("-"):
                continue
                
            # Match pattern: - **[[Target Title]]** (type): justification
            match = re.search(r"-\s*\*\*\[\[(.*?)\]\]\*\*\s*\((.*?)\)", line)
            if match:
                target_title = match.group(1).strip()
                target_id = title_to_arxiv.get(target_title.lower())
                
                if target_id:
                    predicted_links.append({
                        "source": source_id,
                        "target": target_id
                    })
                    
    return predicted_links

def compute_metrics(pred_edges: set[tuple[str, str]], gold_edges: set[tuple[str, str]]) -> dict:
    """
    Compute Precision, Recall, and F1-score for directed edges.
    """
    tp = len(pred_edges & gold_edges)
    precision = tp / len(pred_edges) if pred_edges else 0.0
    recall = tp / len(gold_edges) if gold_edges else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0.0
    
    return {
        "n_predicted": len(pred_edges),
        "n_gold": len(gold_edges),
        "true_positives": tp,
        "precision": round(precision, 5),
        "recall": round(recall, 5),
        "f1": round(f1, 5)
    }

def main():
    notes_dir = Path("data/generated_notes")
    emile_ids_path = Path("data/gold_labels/emile_vault_arxiv_ids.json")
    emile_links_path = Path("data/gold_labels/link_gold.json")
    s2_links_path = Path("data/gold_labels/citations_gold.json")
    output_path = Path("data/results/link_eval.json")
    
    # Pre-checks
    for p in [notes_dir, emile_ids_path, emile_links_path, s2_links_path]:
        if not p.exists():
            print(f"Error: Required path {p} does not exist. Please run setup scripts first.")
            return

    # 1. Load mappings and gold links
    with open(emile_ids_path, encoding="utf-8") as f:
        emile_ids = json.load(f)
    with open(emile_links_path, encoding="utf-8") as f:
        emile_links = json.load(f)
    with open(s2_links_path, encoding="utf-8") as f:
        s2_links = json.load(f)

    # Standardize expert arXiv ID map keys (lowercase)
    emile_title_to_arxiv = {title.lower().strip(): arxiv_id for title, arxiv_id in emile_ids.items()}

    # 2. Build title map from generated notes
    title_to_arxiv = {}
    for note_path in notes_dir.glob("*.md"):
        arxiv_id = note_path.stem
        try:
            content = note_path.read_text(encoding="utf-8")
        except Exception:
            continue
        title_match = re.search(r'^title:\s*"(.*?)"', content, re.MULTILINE)
        if not title_match:
            title_match = re.search(r'^title:\s*(.*?)$', content, re.MULTILINE)
        if title_match:
            title = title_match.group(1).strip().strip('"').strip("'")
            title_to_arxiv[title.lower()] = arxiv_id
            
    # Add Emile's titles to resolver map
    for title, arxiv_id in emile_ids.items():
        if title.lower() not in title_to_arxiv:
            title_to_arxiv[title.lower()] = arxiv_id

    # 3. Parse predicted links
    predicted_links = parse_predicted_links(notes_dir, title_to_arxiv)
    
    # 4. Resolve paper-to-paper links from Emile's vault (Level B Gold)
    gold_emile_links = []
    for el in emile_links:
        if el.get("source_type") != "paper" or el.get("target_type") != "paper":
            continue
            
        src_title = el["source"]
        tgt_title = el["target"]
        
        src_id = emile_title_to_arxiv.get(src_title.lower().strip()) or title_to_arxiv.get(src_title.lower().strip())
        tgt_id = emile_title_to_arxiv.get(tgt_title.lower().strip()) or title_to_arxiv.get(tgt_title.lower().strip())
        
        if src_id and tgt_id:
            gold_emile_links.append({"source": src_id, "target": tgt_id})

    # 5. Extract sets of active paper IDs
    corpus_arxiv_ids = {p.stem for p in notes_dir.glob("*.md")}
    expert_arxiv_ids = set(emile_ids.values())
    intersecting_arxiv_ids = corpus_arxiv_ids & expert_arxiv_ids

    # =========================================================================
    # Level A Evaluation: Global Citations (S2 Graph) over Full Corpus (N=40)
    # =========================================================================
    pred_edges_a = {(l["source"], l["target"]) for l in predicted_links}
    
    # Filter gold citation links to only keep links within our 40-paper corpus
    gold_edges_a = {
        (l["source"], l["target"]) for l in s2_links 
        if l["source"] in corpus_arxiv_ids and l["target"] in corpus_arxiv_ids
    }
    
    metrics_a = compute_metrics(pred_edges_a, gold_edges_a)

    # =========================================================================
    # Level B Evaluation: Personal Vault (Emile Graph) over Overlap Corpus (N=22)
    # =========================================================================
    # Filter predicted links to only keep edges within the 22 shared papers
    pred_edges_b = {
        (src, tgt) for src, tgt in pred_edges_a 
        if src in intersecting_arxiv_ids and tgt in intersecting_arxiv_ids
    }
    
    # Filter Emile's gold links to only keep edges within the 22 shared papers
    gold_edges_b = {
        (l["source"], l["target"]) for l in gold_emile_links 
        if l["source"] in intersecting_arxiv_ids and l["target"] in intersecting_arxiv_ids
    }
    
    metrics_b = compute_metrics(pred_edges_b, gold_edges_b)

    # 6. Save results
    results = {
        "evaluation_scope": "RQ3 - Link Prediction Reliability",
        "level_a_global_citations": {
            "description": "Evaluated on all 40 papers in the corpus against the Semantic Scholar citation graph.",
            "metrics": metrics_a
        },
        "level_b_personal_vault": {
            "description": "Evaluated on the 22 overlapping papers against Emile's Obsidian vault paper-to-paper links.",
            "metrics": metrics_b
        }
    }
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    # Print formatted output
    print("\n" + "="*60)
    print("                RQ3 LINK EVALUATION RESULTS")
    print("="*60)
    print("LEVEL A: GLOBAL CITATIONS (Semantic Scholar API, N=40)")
    print(f"  Predicted Links:    {metrics_a['n_predicted']}")
    print(f"  Gold Citation Links: {metrics_a['n_gold']}")
    print(f"  True Positives:     {metrics_a['true_positives']}")
    print(f"  Directed Precision: {metrics_a['precision']:.5f}")
    print(f"  Directed Recall:    {metrics_a['recall']:.5f}")
    print(f"  Directed F1-score:  {metrics_a['f1']:.5f}")
    print("-"*60)
    print("LEVEL B: PERSONAL VAULT (Emile's Obsidian Vault, N=22)")
    print(f"  Predicted Links:    {metrics_b['n_predicted']}")
    print(f"  Gold Vault Links:   {metrics_b['n_gold']}")
    print(f"  True Positives:     {metrics_b['true_positives']}")
    print(f"  Directed Precision: {metrics_b['precision']:.5f}")
    print(f"  Directed Recall:    {metrics_b['recall']:.5f}")
    print(f"  Directed F1-score:  {metrics_b['f1']:.5f}")
    print("="*60 + "\n")
    print(f"Results successfully saved to {output_path}")

if __name__ == "__main__":
    main()
